plugins: 
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'gems/**/*'
    - '~/.loca/**/*'
    - 'db/schema.rb'
    - 'lib/clients/backup/backup.rb'

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30