FROM ruby:3.3.4

WORKDIR /home/app

ARG PORT=3000

EXPOSE $PORT

RUN apt-get update -qq && apt-get install -y nodejs npm
RUN npm install -g yarn

RUN gem install rails bundler
RUN gem install rails

COPY yarn.lock package.json package-lock.json ./
RUN yarn install --check-files

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

ENTRYPOINT ["/home/app/bin/docker-entrypoint"]
CMD [ "./bin/rails", "server", "--binding=0.0.0.0"]