services:
  database-test:
    image: 'postgres:17.2'
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRESS_DB: test
    networks:
      - database-net
    volumes:
      - ./storage/postgress-test/data/:/var/lib/postgresql/data/
networks: 
  database-net:
    driver: bridge