name: Linter
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run linters
        run: bundle exec rubocop

      # - name: Run linters
      #   run: |
      #     bundle exec rubocop
      #     # bin/stylelint
      #     # bin/prettier
      #     # bin/eslint
      # - name: Run security checks
      #   run: |
      #     bin/bundler-audit --update
      #     bin/brakeman -q -w2
